const $ = (selector) => document.querySelector(selector);
const state = { posts: [], current: null, dirty: false, preview: true };
const fields = ['title', 'description', 'pubDate', 'draft', 'pinned', 'body'];
const escapeHtml = (value) => value.replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char]));
const inline = (value) => escapeHtml(value).replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img alt="$1" src="$2">').replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/\*([^*]+)\*/g, '<em>$1</em>').replace(/`([^`]+)`/g, '<code>$1</code>');
const markdown = (source) => {
  if (/<(?:p|div|h[1-6]|blockquote|ul|ol)\b/i.test(source)) return source;
  const lines = source.trim().split(/\n/); let html = '', list = false;
  const closeList = () => { if (list) { html += '</ul>'; list = false; } };
  for (const line of lines) {
    if (/^\s*$/.test(line)) { closeList(); continue; }
    const heading = line.match(/^(#{1,3})\s+(.+)/); const bullet = line.match(/^\s*[-*]\s+(.+)/); const quote = line.match(/^>\s?(.+)/);
    if (heading) { closeList(); html += `<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`; }
    else if (bullet) { if (!list) { html += '<ul>'; list = true; } html += `<li>${inline(bullet[1])}</li>`; }
    else if (quote) { closeList(); html += `<blockquote>${inline(quote[1])}</blockquote>`; }
    else { closeList(); html += `<p>${inline(line)}</p>`; }
  }
  closeList(); return html;
};
const updateCount = () => { const count = $('#body').value.trim() ? $('#body').value.trim().split(/\s+/).length : 0; $('#word-count').textContent = `${count.toLocaleString()} ${count === 1 ? 'word' : 'words'}`; };
const updatePreview = () => { if (!state.current) return; $('#preview').innerHTML = `<h1>${escapeHtml($('#title').value || 'Untitled post')}</h1><p class="preview-description">${escapeHtml($('#description').value || '')}</p><p class="preview-date">${$('#pubDate').value || ''}</p>${markdown($('#body').value)}`; };
const setDirty = () => { state.dirty = true; $('#save-state').textContent = 'Unsaved changes'; $('#save-post').disabled = false; updateCount(); updatePreview(); };
const loadPosts = async () => { state.posts = await (await fetch('/api/posts')).json(); $('#post-count').textContent = state.posts.length; $('#post-list').innerHTML = state.posts.sort((a,b) => (b.pubDate || '').localeCompare(a.pubDate || '')).map((post) => { const isDraft = post.draft === true; return `<button class="post-item ${state.current?.slug === post.slug ? 'active' : ''}" data-slug="${post.slug}"><strong>${isDraft ? '<span class="draft-dot"></span>' : ''}${escapeHtml(post.title)}</strong><small>${isDraft ? 'Draft' : (post.pubDate || 'No date')}</small></button>`; }).join(''); document.querySelectorAll('.post-item').forEach((item) => item.onclick = () => openPost(item.dataset.slug)); };
const openPost = async (slug) => { if (state.dirty && !confirm('Discard your unsaved changes?')) return; state.current = await (await fetch(`/api/posts/${encodeURIComponent(slug)}`)).json(); fields.forEach((field) => { const element = $(`#${field}`); if (element.type === 'checkbox') element.checked = state.current[field]; else element.value = state.current[field] || ''; }); state.dirty = false; $('#save-state').textContent = 'Saved'; $('#save-post').disabled = false; $('#empty-state').classList.add('hidden'); $('#editor-view').classList.remove('hidden'); updateCount(); updatePreview(); await loadPosts(); };
const newPost = () => { state.current = { slug: `untitled-${Date.now()}`, title: '', description: '', pubDate: new Date().toISOString().slice(0,10), draft: true, pinned: false, body: '' }; fields.forEach((field) => { const element = $(`#${field}`); if (element.type === 'checkbox') element.checked = state.current[field]; else element.value = state.current[field] || ''; }); state.dirty = true; $('#save-state').textContent = 'New draft'; $('#save-post').disabled = false; $('#empty-state').classList.add('hidden'); $('#editor-view').classList.remove('hidden'); $('#title').focus(); updateCount(); updatePreview(); };
const save = async () => { if (!state.current) return; const payload = { ...state.current, ...Object.fromEntries(fields.map((field) => { const element = $(`#${field}`); return [field, element.type === 'checkbox' ? element.checked : element.value]; })) }; let slug = state.current.slug; if (state.current.slug.startsWith('untitled-')) slug = payload.title.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || state.current.slug; const response = await fetch(`/api/posts/${encodeURIComponent(slug)}`, { method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) }); if (!response.ok) return alert((await response.json()).error); state.current = { ...state.current, ...payload, slug }; state.dirty = false; $('#save-state').textContent = 'Saved just now'; await loadPosts(); };
const uploadImage = async (file) => { if (!state.current) return alert('Create or open a post first.'); if (state.current.slug.startsWith('untitled-')) { await save(); if (state.current.slug.startsWith('untitled-')) return; } const safeName = file.name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-'); const data = await new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(file); }); const response = await fetch('/api/images', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ slug:state.current.slug, filename:safeName, data }) }); if (!response.ok) return alert((await response.json()).error); const result = await response.json(); const alt = prompt('Image description (alt text):', file.name.replace(/\.[^.]+$/, '').replaceAll('-', ' ')) || ''; const start = $('#body').selectionStart; $('#body').value = `${$('#body').value.slice(0, start)}\n\n![${alt}](${result.path})\n\n${$('#body').value.slice(start)}`; setDirty(); };
fields.forEach((field) => $(`#${field}`).addEventListener('input', setDirty)); $('#new-post').onclick = newPost; $('#empty-new').onclick = newPost; $('#save-post').onclick = save; $('#preview-toggle').onclick = () => { state.preview = !state.preview; $('#preview').style.display = state.preview ? '' : 'none'; $('#preview-toggle').textContent = state.preview ? 'Preview' : 'Show preview'; }; $('#body').addEventListener('paste', (event) => { const file = [...(event.clipboardData?.files || [])][0]; if (file?.type.startsWith('image/')) { event.preventDefault(); uploadImage(file); } }); $('#body').addEventListener('dragover', (event) => event.preventDefault()); $('#body').addEventListener('drop', (event) => { event.preventDefault(); const file = [...event.dataTransfer.files][0]; if (file?.type.startsWith('image/')) uploadImage(file); });
document.addEventListener('keydown', (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 's') { event.preventDefault(); save(); } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'n') { event.preventDefault(); newPost(); } });
loadPosts();
